### ISSUE TITLE
Google Cloud Storage: File not found when downloading blob using GCS URI

### ISSUE THREAD

**Issue by arinto** [googleapis/google-cloud-python#8614]
#### Environment details

1. OS type and version: MacOS 10.14.5
1. Python version and virtual environment information:` Python 3.6.8 :: Anaconda, Inc`.
1. google-cloud-storage version:  
```
Name: google-cloud-storage
Version: 1.16.1
Summary: Google Cloud Storage API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages
Requires: google-auth, google-resumable-media, google-cloud-core
Required-by: kfp
```

#### Steps to reproduce

  1. Run the code example

#### Code example

```python
import pathlib
import google.cloud.storage as gcs

client = gcs.Client()
target = pathlib.Path("shakespeare1.txt")
gcs_path="gs://ml-pipeline-playground/shakespeare1.txt"

with target.open(mode="wb") as downloaded_file:
        client.download_blob_to_file(gcs_path, downloaded_file)
```

#### Stack trace
```
/Users/arinto/anaconda3/envs/anaconda-env/bin/python /Volumes/tvlk-repo/github/dummy-repo/dummy_module/bug.py
/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
Traceback (most recent call last):
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/cloud/storage/client.py", line 387, in download_blob_to_file
    blob_or_uri.download_to_file(file_obj, client=self, start=start, end=end)
AttributeError: 'str' object has no attribute 'download_to_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 636, in download_to_file
    self._do_download(transport, file_obj, download_url, headers, start, end)
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 574, in _do_download
    download.consume(transport)
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/resumable_media/requests/download.py", line 171, in consume
    self._process_response(result)
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/resumable_media/_download.py", line 170, in _process_response
    response, _ACCEPTABLE_STATUS_CODES, self._get_status_code)
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/resumable_media/_helpers.py", line 93, in require_status_code
    status_code, u'Expected one of', *status_codes
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/tvlk-repo/github/dummy-repo/dummy_module/bug.py", line 10, in <module>
    client.download_blob_to_file(gcs_path, downloaded_file)
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/cloud/storage/client.py", line 395, in download_blob_to_file
    blob_or_uri.download_to_file(file_obj, client=self, start=start, end=end)
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 638, in download_to_file
    _raise_from_invalid_response(exc)
  File "/Users/arinto/anaconda3/envs/anaconda-env/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2034, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.NotFound: 404 GET https://www.googleapis.com/download/storage/v1/b/ml-pipeline-playground/o/%2Fshakespeare1.txt?alt=media: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

Process finished with exit code 1
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by arinto** [comment]
Apparently it has been fixed in a9d9cca1738115c85406da047add13d820eb1a65 but not yet released. Will close this issue.

**Comment by jenildesai25** [comment]
I am still facing still issue. I assume it would be merged by now?
